title: Introduction
author: GitHub User
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  HI my name is fan, and this is my first ever website i have created but im still learning and i hope i can improve my skill and make the better one in the future :)
theme: minima
# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
